In [1]:
import pandas as pd

In [2]:
res  = pd.read_csv('../../results/FinalResultsADEPTNew.csv')
res.head()

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
0,microsoft/deberta-base,concreteness_score_addition,train,1,0.692737,0.421802,0.355937,0.376892,0.732225,0.710918,0.437167,0.355651,0.381041,0.748062
1,microsoft/deberta-base,concreteness_score_addition,train,2,0.697083,0.423899,0.370494,0.389760,0.747151,0.716501,0.443234,0.375692,0.399110,0.752123
2,microsoft/deberta-base,concreteness_score_addition,train,3,0.695220,0.434807,0.381118,0.398491,0.741670,0.697270,0.413870,0.371110,0.385685,0.757999
3,microsoft/deberta-base,concreteness_score_addition,train,4,0.675978,0.414134,0.393301,0.398001,0.748236,0.687965,0.402670,0.384769,0.389635,0.761849
4,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,1,0.703911,0.466361,0.284447,0.302450,0.725522,0.704715,0.463664,0.267322,0.282410,0.726188

In [4]:
res[res.model_name == "facebook/bart-base"].sort_values(by=['test_accuracy'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
18,facebook/bart-base,concreteness_score_addition,train,3,0.698324,0.425392,0.353423,0.376100,0.743411,0.725806,0.465210,0.368696,0.398438,0.775411
27,facebook/bart-base,normal_finetuning,train,4,0.696462,0.426166,0.373465,0.392378,0.732624,0.722084,0.454838,0.391489,0.415188,0.776406
26,facebook/bart-base,normal_finetuning,train,3,0.705152,0.441156,0.366145,0.388580,0.730755,0.721464,0.465068,0.365629,0.393769,0.773751

In [5]:
res[res.model_name == "facebook/bart-base"].sort_values(by=['test_roc_auc'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
27,facebook/bart-base,normal_finetuning,train,4,0.696462,0.426166,0.373465,0.392378,0.732624,0.722084,0.454838,0.391489,0.415188,0.776406
18,facebook/bart-base,concreteness_score_addition,train,3,0.698324,0.425392,0.353423,0.376100,0.743411,0.725806,0.465210,0.368696,0.398438,0.775411
26,facebook/bart-base,normal_finetuning,train,3,0.705152,0.441156,0.366145,0.388580,0.730755,0.721464,0.465068,0.365629,0.393769,0.773751

In [8]:
res[((res.model_name == "facebook/bart-base") & (res.train_dataset_type == "artificial_train_combined"))].sort_values(by=['test_roc_auc'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
31,facebook/bart-base,normal_finetuning,artificial_train_combined,4,0.692117,0.420870,0.374169,0.390069,0.741544,0.704094,0.442577,0.386574,0.404642,0.751141
30,facebook/bart-base,normal_finetuning,artificial_train_combined,3,0.639975,0.396843,0.368332,0.365461,0.739361,0.660050,0.416617,0.381048,0.380903,0.749784
21,facebook/bart-base,concreteness_score_addition,artificial_train_combined,2,0.707635,0.448964,0.345119,0.373706,0.732130,0.711538,0.440924,0.332193,0.361647,0.748646

In [9]:
res[((res.model_name == "facebook/bart-base") & (res.train_dataset_type == "artificial_train_combined"))].sort_values(by=['test_accuracy'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
21,facebook/bart-base,concreteness_score_addition,artificial_train_combined,2,0.707635,0.448964,0.345119,0.373706,0.732130,0.711538,0.440924,0.332193,0.361647,0.748646
29,facebook/bart-base,normal_finetuning,artificial_train_combined,2,0.689013,0.410815,0.340143,0.360883,0.721788,0.707816,0.450657,0.359383,0.387891,0.737851
23,facebook/bart-base,concreteness_score_addition,artificial_train_combined,4,0.692737,0.422391,0.377469,0.390704,0.743697,0.705955,0.439848,0.374400,0.394190,0.745674

In [14]:
res[res.model_name == "microsoft/deberta-base"].sort_values(by=['test_accuracy'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
1,microsoft/deberta-base,concreteness_score_addition,train,2,0.697083,0.423899,0.370494,0.389760,0.747151,0.716501,0.443234,0.375692,0.399110,0.752123
0,microsoft/deberta-base,concreteness_score_addition,train,1,0.692737,0.421802,0.355937,0.376892,0.732225,0.710918,0.437167,0.355651,0.381041,0.748062
14,microsoft/deberta-base,normal_finetuning,artificial_train_combined,3,0.706394,0.441522,0.323535,0.335554,0.702527,0.705955,0.436631,0.310239,0.318772,0.714361

In [18]:
res[res.model_name == "microsoft/deberta-base"].sort_values(by=['test_roc_auc'], ascending=False).head(5)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
6,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,3,0.700807,0.433721,0.359241,0.383321,0.750411,0.701613,0.416728,0.357466,0.379014,0.762923
3,microsoft/deberta-base,concreteness_score_addition,train,4,0.675978,0.414134,0.393301,0.398001,0.748236,0.687965,0.402670,0.384769,0.389635,0.761849
7,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,4,0.685289,0.420415,0.403362,0.408644,0.751175,0.675558,0.395915,0.376080,0.382074,0.760869
2,microsoft/deberta-base,concreteness_score_addition,train,3,0.695220,0.434807,0.381118,0.398491,0.741670,0.697270,0.413870,0.371110,0.385685,0.757999
5,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,2,0.700186,0.431362,0.370173,0.390604,0.754458,0.702854,0.430742,0.372480,0.391670,0.757785

In [19]:
res[(res.model_name == "microsoft/deberta-base") & (res.strategy == "normal_finetuning")].sort_values(by=['test_roc_auc'], ascending=False).head(5)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
14,microsoft/deberta-base,normal_finetuning,artificial_train_combined,3,0.706394,0.441522,0.323535,0.335554,0.702527,0.705955,0.436631,0.310239,0.318772,0.714361
15,microsoft/deberta-base,normal_finetuning,artificial_train_combined,4,0.698945,0.422493,0.381530,0.396307,0.702633,0.694789,0.405388,0.354004,0.372079,0.707460
13,microsoft/deberta-base,normal_finetuning,artificial_train_combined,2,0.684668,0.310395,0.274806,0.274676,0.695962,0.682382,0.294625,0.265323,0.264748,0.673954
12,microsoft/deberta-base,normal_finetuning,artificial_train_combined,1,0.664184,0.132837,0.200000,0.159642,0.616589,0.683623,0.136725,0.200000,0.162417,0.627325
9,microsoft/deberta-base,normal_finetuning,train,2,0.664184,0.132837,0.200000,0.159642,0.509658,0.683623,0.136725,0.200000,0.162417,0.517204

In [20]:
res[(res.model_name == "microsoft/deberta-base") & (res.strategy == "concreteness_score_addition")].sort_values(by=['test_roc_auc'], ascending=False).head(5)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
6,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,3,0.700807,0.433721,0.359241,0.383321,0.750411,0.701613,0.416728,0.357466,0.379014,0.762923
3,microsoft/deberta-base,concreteness_score_addition,train,4,0.675978,0.414134,0.393301,0.398001,0.748236,0.687965,0.402670,0.384769,0.389635,0.761849
7,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,4,0.685289,0.420415,0.403362,0.408644,0.751175,0.675558,0.395915,0.376080,0.382074,0.760869
2,microsoft/deberta-base,concreteness_score_addition,train,3,0.695220,0.434807,0.381118,0.398491,0.741670,0.697270,0.413870,0.371110,0.385685,0.757999
5,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,2,0.700186,0.431362,0.370173,0.390604,0.754458,0.702854,0.430742,0.372480,0.391670,0.757785

In [21]:
res[((res.model_name == "microsoft/deberta-base") & (res.train_dataset_type == "artificial_train_combined") & (res.strategy == "normal_finetuning"))].sort_values(by=['test_roc_auc'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
14,microsoft/deberta-base,normal_finetuning,artificial_train_combined,3,0.706394,0.441522,0.323535,0.335554,0.702527,0.705955,0.436631,0.310239,0.318772,0.714361
15,microsoft/deberta-base,normal_finetuning,artificial_train_combined,4,0.698945,0.422493,0.381530,0.396307,0.702633,0.694789,0.405388,0.354004,0.372079,0.707460
13,microsoft/deberta-base,normal_finetuning,artificial_train_combined,2,0.684668,0.310395,0.274806,0.274676,0.695962,0.682382,0.294625,0.265323,0.264748,0.673954

In [16]:
res[((res.model_name == "microsoft/deberta-base") & (res.train_dataset_type == "artificial_train_combined"))].sort_values(by=['test_roc_auc'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
6,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,3,0.700807,0.433721,0.359241,0.383321,0.750411,0.701613,0.416728,0.357466,0.379014,0.762923
7,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,4,0.685289,0.420415,0.403362,0.408644,0.751175,0.675558,0.395915,0.376080,0.382074,0.760869
5,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,2,0.700186,0.431362,0.370173,0.390604,0.754458,0.702854,0.430742,0.372480,0.391670,0.757785

In [17]:
res[((res.model_name == "microsoft/deberta-base") & (res.train_dataset_type == "artificial_train_combined"))].sort_values(by=['test_accuracy'], ascending=False).head(3)

,model_name,strategy,train_dataset_type,epoch,validation_accuracy,validation_precision,validation_recall,validation_f1,validation_roc_auc,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
14,microsoft/deberta-base,normal_finetuning,artificial_train_combined,3,0.706394,0.441522,0.323535,0.335554,0.702527,0.705955,0.436631,0.310239,0.318772,0.714361
4,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,1,0.703911,0.466361,0.284447,0.302450,0.725522,0.704715,0.463664,0.267322,0.282410,0.726188
5,microsoft/deberta-base,concreteness_score_addition,artificial_train_combined,2,0.700186,0.431362,0.370173,0.390604,0.754458,0.702854,0.430742,0.372480,0.391670,0.757785