In [1]:
from transformers import AutoTokenizer, AutoModel

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
checkpoint = "bert-base-uncased"

In [3]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [4]:
import datasets

In [5]:
mrpc_dataset = datasets.load_dataset("glue", "mrpc")

In [6]:
mrpc_dataset

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

In [7]:
mrpc_dataset['train']

Dataset({
    features: ['sentence1', 'sentence2', 'label', 'idx'],
    num_rows: 3668
})

In [8]:
mrpc_dataset['train'][0]

{'sentence1': 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 'sentence2': 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 'label': 1,
 'idx': 0}

In [9]:
mrpc_dataset['train'].features

{'sentence1': Value(dtype='string', id=None),
 'sentence2': Value(dtype='string', id=None),
 'label': ClassLabel(names=['not_equivalent', 'equivalent'], id=None),
 'idx': Value(dtype='int32', id=None)}

In [10]:
mrpc_dataset['train'][14]

{'sentence1': 'Gyorgy Heizler , head of the local disaster unit , said the coach was carrying 38 passengers .',
 'sentence2': 'The head of the local disaster unit , Gyorgy Heizler , said the coach driver had failed to heed red stop lights .',
 'label': 0,
 'idx': 15}

In [11]:
mrpc_dataset['validation'][86]

{'sentence1': 'He was arrested Friday night at an Alpharetta seafood restaurant while dining with his wife , singer Whitney Houston .',
 'sentence2': 'He was arrested again Friday night at an Alpharetta restaurant where he was having dinner with his wife .',
 'label': 1,
 'idx': 796}

#### Let's try tokenizing pairs of sentences together

In [12]:
sentences = [
    ['My name is Sarthak Singh.', 'I am from New Delhi'],
    ['The course is already hard enough.', "And now I have taken too many subjects as well"]
]

In [13]:
tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")

{'input_ids': tensor([[  101,  2026,  2171,  2003, 18906,  8322,  2243,  5960,  1012,   102,
          1045,  2572,  2013,  2047,  6768,   102,     0,     0,     0,     0],
        [  101,  1996,  2607,  2003,  2525,  2524,  2438,  1012,   102,  1998,
          2085,  1045,  2031,  2579,  2205,  2116,  5739,  2004,  2092,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

token_type_ids tell us which sentence does the tokens belong to

In [14]:
tokenizer(mrpc_dataset['train'][14]['sentence1'], mrpc_dataset['train'][14]['sentence2'], padding=True, truncation=True, return_tensors="pt")

{'input_ids': tensor([[  101,  1043,  7677, 22637,  2002, 10993,  3917,  1010,  2132,  1997,
          1996,  2334,  7071,  3131,  1010,  2056,  1996,  2873,  2001,  4755,
          4229,  5467,  1012,   102,  1996,  2132,  1997,  1996,  2334,  7071,
          3131,  1010,  1043,  7677, 22637,  2002, 10993,  3917,  1010,  2056,
          1996,  2873,  4062,  2018,  3478,  2000, 18235,  2094,  2417,  2644,
          4597,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1]])}

In [15]:
tokenizer(mrpc_dataset['train'][14]['sentence1'], padding=True, truncation=True, return_tensors="pt")

{'input_ids': tensor([[  101,  1043,  7677, 22637,  2002, 10993,  3917,  1010,  2132,  1997,
          1996,  2334,  7071,  3131,  1010,  2056,  1996,  2873,  2001,  4755,
          4229,  5467,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [16]:
tokenizer(mrpc_dataset['train'][14]['sentence2'], padding=True, truncation=True, return_tensors="pt")

{'input_ids': tensor([[  101,  1996,  2132,  1997,  1996,  2334,  7071,  3131,  1010,  1043,
          7677, 22637,  2002, 10993,  3917,  1010,  2056,  1996,  2873,  4062,
          2018,  3478,  2000, 18235,  2094,  2417,  2644,  4597,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]])}

In [17]:
mrpc_dataset['train'][14]

{'sentence1': 'Gyorgy Heizler , head of the local disaster unit , said the coach was carrying 38 passengers .',
 'sentence2': 'The head of the local disaster unit , Gyorgy Heizler , said the coach driver had failed to heed red stop lights .',
 'label': 0,
 'idx': 15}

##### Fixed Size Padding

In [18]:
def tokenize_sentences_function(item):
    return tokenizer(item['sentence1'], item['sentence2'], padding="max_length", truncation=True, max_length=128)

In [19]:
tokenized_dataset = mrpc_dataset.map(tokenize_sentences_function, batched=True)

Map: 100%|██████████| 3668/3668 [00:00<00:00, 12100.44 examples/s]

In [20]:
tokenized_dataset.column_names

{'train': ['sentence1',
  'sentence2',
  'label',
  'idx',
  'input_ids',
  'token_type_ids',
  'attention_mask'],
 'validation': ['sentence1',
  'sentence2',
  'label',
  'idx',
  'input_ids',
  'token_type_ids',
  'attention_mask'],
 'test': ['sentence1',
  'sentence2',
  'label',
  'idx',
  'input_ids',
  'token_type_ids',
  'attention_mask']}

In [21]:
tokenized_dataset = tokenized_dataset.remove_columns(['sentence1', 'sentence2', 'idx'])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset = tokenized_dataset.with_format("torch")
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [22]:
print(tokenizer.convert_ids_to_tokens(tokenized_dataset['train'][14]['input_ids']))

['[CLS]', 'g', '##yo', '##rgy', 'he', '##iz', '##ler', ',', 'head', 'of', 'the', 'local', 'disaster', 'unit', ',', 'said', 'the', 'coach', 'was', 'carrying', '38', 'passengers', '.', '[SEP]', 'the', 'head', 'of', 'the', 'local', 'disaster', 'unit', ',', 'g', '##yo', '##rgy', 'he', '##iz', '##ler', ',', 'said', 'the', 'coach', 'driver', 'had', 'failed', 'to', 'hee', '##d', 'red', 'stop', 'lights', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']

In [23]:
from torch.utils.data import DataLoader

In [24]:
train_dataloader = DataLoader(tokenized_dataset['train'], batch_size=16, shuffle=True)

In [25]:
for step, batch in enumerate(train_dataloader):
    print(batch['input_ids'].shape)
    if step>5:
        break

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Here, each batch has a fixed length padding

##### Dynamic Padding

In [26]:
def tokenize_sentences_function(item):
    return tokenizer(item['sentence1'], item['sentence2'], truncation=True)

In [27]:
tokenized_dataset = mrpc_dataset.map(tokenize_sentences_function, batched=True)

Map: 100%|██████████| 408/408 [00:00<00:00, 20448.53 examples/s]

In [28]:
tokenized_dataset = tokenized_dataset.remove_columns(['sentence1', 'sentence2', 'idx'])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset = tokenized_dataset.with_format("torch")
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [29]:
from transformers import DataCollatorWithPadding

Data collator is responsible for applying all the necessary preprocessing needed before applying the batch

In [30]:
data_collator = DataCollatorWithPadding(tokenizer)

In [31]:
train_dataloader = DataLoader(tokenized_dataset['train'], batch_size=16, shuffle=True, collate_fn=data_collator)

In [32]:
for step, batch in enumerate(train_dataloader):
    print(batch['input_ids'].shape)
    if step>5:
        break

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

torch.Size([16, 68])
torch.Size([16, 77])
torch.Size([16, 74])
torch.Size([16, 71])
torch.Size([16, 77])
torch.Size([16, 81])
torch.Size([16, 78])

##### Training

In [33]:
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification

In [34]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [35]:
training_args = TrainingArguments("test-train",
                                 per_device_train_batch_size=16,
                                 per_device_eval_batch_size=16,
                                 num_train_epochs=5,
                                 learning_rate=2e-5,
                                 weight_decay=0.01)

In [37]:
trainer = Trainer(model,
                  training_args,
                 train_dataset=tokenized_dataset['train'],
                 eval_dataset=tokenized_dataset['validation'],
                 data_collator=data_collator,
                 tokenizer=tokenizer)

In [38]:
trainer.train()

TrainOutput(global_step=1150, training_loss=0.22636954722197158, metrics={'train_runtime': 222.9248, 'train_samples_per_second': 82.27, 'train_steps_per_second': 5.159, 'total_flos': 717074236946640.0, 'train_loss': 0.22636954722197158, 'epoch': 5.0})

In [39]:
import torch
torch.cuda.is_available()

True

In [40]:
predictions = trainer.predict(tokenized_dataset['validation'])
print(predictions.predictions.shape, predictions.label_ids.shape)

(408, 2) (408,)

In [41]:
import numpy as np

In [42]:
from datasets import load_metric

In [43]:
metric = load_metric("glue", "mrpc")

/tmp/ipykernel_932/442538619.py:1: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("glue", "mrpc")
/usr/local/lib/python3.10/site-packages/datasets/load.py:752: FutureWarning: The repository for glue contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.16.1/metrics/glue/glue.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(
Downloading builder script: 5.76kB [00:00, 8.26MB/s]

In [45]:
metric

Metric(name: "glue", features: {'predictions': Value(dtype='int64', id=None), 'references': Value(dtype='int64', id=None)}, usage: """
Compute GLUE evaluation metric associated to each GLUE dataset.
Args:
    predictions: list of predictions to score.
        Each translation should be tokenized into a list of tokens.
    references: list of lists of references for each translation.
        Each reference should be tokenized into a list of tokens.
Returns: depending on the GLUE subset, one or several of:
    "accuracy": Accuracy
    "f1": F1 score
    "pearson": Pearson Correlation
    "spearmanr": Spearman Correlation
    "matthews_correlation": Matthew Correlation
Examples:

    >>> glue_metric = datasets.load_metric('glue', 'sst2')  # 'sst2' or any of ["mnli", "mnli_mismatched", "mnli_matched", "qnli", "rte", "wnli", "hans"]
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'accuracy': 1.0}

    >>> glue_metric = datasets.load_metric('glue', 'mrpc')  # 'mrpc' or 'qqp'
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'accuracy': 1.0, 'f1': 1.0}

    >>> glue_metric = datasets.load_metric('glue', 'stsb')
    >>> references = [0., 1., 2., 3., 4., 5.]
    >>> predictions = [0., 1., 2., 3., 4., 5.]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print({"pearson": round(results["pearson"], 2), "spearmanr": round(results["spearmanr"], 2)})
    {'pearson': 1.0, 'spearmanr': 1.0}

    >>> glue_metric = datasets.load_metric('glue', 'cola')
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'matthews_correlation': 1.0}
""", stored examples: 0)

In [46]:
preds = np.argmax(predictions.predictions, axis=-1)

In [48]:
metric.compute(predictions=preds, references=predictions.label_ids)

{'accuracy': 0.8529411764705882, 'f1': 0.8951048951048952}

In [49]:
def compute_metrics(eval_preds):
    logits, labels = eval_preds
    preds = np.argmax(logits, axis=-1)
    return metric.compute(predictions=preds, references=labels)

In [52]:
training_args = TrainingArguments("test-train",
                                 per_device_train_batch_size=16,
                                 per_device_eval_batch_size=16,
                                 num_train_epochs=2,
                                 learning_rate=2e-5,
                                 weight_decay=0.01,
                                 evaluation_strategy="epoch")

In [53]:
trainer = Trainer(model,
                  training_args,
                 train_dataset=tokenized_dataset['train'],
                 eval_dataset=tokenized_dataset['validation'],
                 data_collator=data_collator,
                 tokenizer=tokenizer,
                 compute_metrics=compute_metrics)

In [54]:
trainer.train()

TrainOutput(global_step=460, training_loss=0.02699071635370669, metrics={'train_runtime': 88.1029, 'train_samples_per_second': 83.266, 'train_steps_per_second': 5.221, 'total_flos': 287354272445280.0, 'train_loss': 0.02699071635370669, 'epoch': 2.0})

##### Training using pure pytorch

In [55]:
def tokenize_sentences_function(item):
    return tokenizer(item['sentence1'], item['sentence2'], truncation=True)

In [56]:
tokenized_dataset = mrpc_dataset.map(tokenize_sentences_function, batched=True)

Map: 100%|██████████| 3668/3668 [00:00<00:00, 16198.59 examples/s]
Map: 100%|██████████| 408/408 [00:00<00:00, 13993.93 examples/s]
Map: 100%|██████████| 1725/1725 [00:00<00:00, 17326.94 examples/s]

In [57]:
tokenized_dataset = tokenized_dataset.remove_columns(['sentence1', 'sentence2', 'idx'])
tokenized_dataset = tokenized_dataset.rename_column("label", "labels")
tokenized_dataset = tokenized_dataset.with_format("torch")
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [58]:
data_collator = DataCollatorWithPadding(tokenizer)

In [60]:
train_dataloader = DataLoader(tokenized_dataset['train'], batch_size=16, shuffle=True, collate_fn=data_collator)
eval_dataloader = DataLoader(tokenized_dataset['validation'], batch_size=16, collate_fn=data_collator)

Let's check

In [65]:
from pprint import pprint

In [66]:
for batch in train_dataloader:
    pprint({k:v.shape for k, v in batch.items()})
    break

{'attention_mask': torch.Size([16, 76]),
 'input_ids': torch.Size([16, 76]),
 'labels': torch.Size([16]),
 'token_type_ids': torch.Size([16, 76])}

In [86]:
bert_model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [87]:
outputs = bert_model(**batch)

In [88]:
outputs.loss, outputs.logits.shape

(tensor(0.7890, grad_fn=<NllLossBackward0>), torch.Size([16, 2]))

In [89]:
from torch.optim.adamw import AdamW

In [90]:
optimizer = AdamW(bert_model.parameters(), lr=5e-5)

In [91]:
loss = outputs.loss
loss

tensor(0.7890, grad_fn=<NllLossBackward0>)

In [92]:
loss.backward()

In [93]:
optimizer.step()

In [94]:
optimizer.zero_grad() # flushing gradient to prevent accumulation

##### LR Scheduler - to progressively decay our learning rate to zero

In [108]:
from transformers import get_scheduler

In [109]:
num_epochs = 3
num_training_steps = num_epochs*len(train_dataloader)

In [110]:
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

In [111]:
bert_model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [112]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
bert_model.to(device)
print(device)

cuda

In [113]:
from tqdm.auto import tqdm

In [114]:
progress_bar = tqdm(range(num_training_steps))
bert_model.train()
for batch in train_dataloader:
    batch = {k: v.to(device) for k, v in batch.items()}
    outputs = bert_model(**batch)
    loss = outputs.loss
    # Calculating gradient
    loss.backward()
    # Optimization
    optimizer.step()
    # Updating Learning Rate
    lr_scheduler.step()
    # Flushing Gradients
    optimizer.zero_grad()
    # Updating Progress Bar
    progress_bar.update(1)

  0%|          | 0/690 [02:10<?, ?it/s]

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!